name: actions-create-release
description: A github action creating releases

inputs:
  GITHUB_TOKEN:
    description: "The Github token to use for creating the release."
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    
    - uses: nowsprinting/check-version-format-action@v3
      id: version
      with:
        prefix: 'v'
        
    - name: Create release
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      run: |
        gh release create "${{steps.version.outputs.full}}" \
            --repo="$GITHUB_REPOSITORY" \
            --title="Release ${{steps.version.outputs.full_without_prefix}}" \
            --generate-notes \
            ${{ steps.version.outputs.is_stable != 'true' && '--prerelease' || '' }}
      shell: bash
